def generate_ephemeral_keypair(as_secp256r1: bool = False) -> dict[str, bytes]: ...
def extract_jwt_claims(jwt: str) -> tuple[str, str, str, str]: ...
def compute_nonce(epk_bytes: bytes, max_epoch: int, randomness: str) -> str: ...
def compute_address_seed(
    key_claim_name: str,
    key_claim_value: str,
    audience: str,
    user_salt: str,
) -> bytes: ...
def compute_zklogin_address(iss: str, address_seed: bytes, legacy: bool) -> str: ...
def build_zklogin_signature(
    proof_json: str,
    ephemeral_sig: bytes,
    address_seed: bytes,
    max_epoch: int,
) -> str: ...
