def generate_ephemeral_keypair() -> dict[str, bytes]: ...
def validate_jwt(jwt: str) -> tuple[str, str, str, str]: ...
def compute_nonce(epk_bytes: bytes, max_epoch: int, randomness: str) -> str: ...
def compute_address_seed(
    key_claim_name: str,
    key_claim_value: str,
    audience: str,
    user_salt: str,
) -> bytes: ...
def compute_zklogin_address(iss: str, address_seed: bytes, legacy: bool) -> str: ...
